[package]
name = "tokenizer"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"
nom_locate = "4.2"
ordered-float = "4.2"
memchr = "2.7"

[dev-dependencies]
rand = "0.8"